format: original
cache: /leonardo_scratch/large/userexternal/ggiulian/cache
datapath: /leonardo_scratch/large/userexternal/ggiulian/run/output
plotpath: /leonardo_scratch/large/userexternal/ggiulian/plots
original:
        simulation: MED-12
        variables:
                pr: STS
                tas: STS
                clt: SRF
                rsnl: RAD
plot:
        biasplot:
                years: [1980]
                name: MED-12 non coupled
                dpi: 100
                seasons: [ "DJF", "MAM", "JJA", "SON" ]
                variables:
                        tas:
                                obs: [ "EOBS", "CRU", "ERA5" ]
                        pr:
                                obs: [ "EOBS", "CRU", "ERA5", "MSWEP", "CPC" ]
                        clt:
                                obs: [ "CRU", "ERA5" ]
                        rsnl:
                                obs: [ "ERA5" ]
        p99plot:
                years: [1980]
                name: MED-12 non coupled
                dpi: 100
                variables:
                        pr:
                                obs: [ "EOBS", "CPC" ]
